### ISSUE TITLE
Chart Export Data example: Save as SVG does not work

### ISSUE THREAD

**Issue by datafj** [syncfusion/winforms-demos#5]
First of all, I can't run the .net framework 4.6 version, because the `Syncfusion.dls.base` nuget package cannot be restored. Nevertheless, the .net 6 version works in Visual Studio 2019.

The example program runs as expected. It also seems to run correctly when click the "SVG" export button. However, the generated "chartexport.svg" file is not actually a svg file. It won't be opened in any SVG viewer. I also found it's not a text-based file as .svg supposed to be, instead it's a binary file. After I changed the file name to "chartexport.png", it can be correctly opened in image viewer. So the "SVG" export button actually generates a png file under a svg file name.

So I went to check the source code , and found no problem with the source code:

```
private void buttonSVG_Click(object sender, EventArgs e)
        {
            try
            {
                exportFileName = fileName + ".svg";
                this.chartControl1.SaveImage(exportFileName);
                OpenFile("Svg", exportFileName);
            }
            catch (Exception ex)
            {
                this.toolStripStatusLabel1.Text = "Chart Export failed.";
                Console.WriteLine(ex.ToString());
            }
        }
```

There were no exception caught either. 

Is this a bug of the `SaveImage` method? SVG export is essential to our work, can someone check the issue?

Thanks!

**Comment by DevakumarD** [comment]
Hi @datafj,

We would like to let you know that the export chart image to SVG format supports in NET Framework version and could you please check by updating the NuGet manually if you face any issue with restoring.

And currently, we don’t have support to export chart image as SVG format in **.NET core** and later version(**.NET6**). We would like to suggest using the .NET framework version to save image in SVG. 

We have considered this as a feature request and added it to our feature request list. You can track the status of this feature from the below feedback portal link.

Feedback link: https://www.syncfusion.com/feedback/37336 

We will prioritize the features in every release based on the demands, and we do not have an immediate plan to implement this since we committed with already planned work. So, this feature will be available for any of our upcoming release.

Please cast your vote to make it count and if you have any more specifications/suggestions to the feature request, you can add it as a comment in the feedback portal.

Regards
Devakumar D

**Comment by JustLoveData** [comment]
Hi @DevakumarD ,

Thank you for your response. Now I see that the SVG export is not available in .NET core, but only in .NET framework.

I understand that your team needs to prioritize the features. However, including the feature in the example when it is not there creates confusion and wastes time of your users. 

Regards
